ISAI APP/ISAI APP/Controllers/FindCropValidateController.cs
using FindAndCropImage;
using ISAI_APP.Models;
using ISAI_APP.OCR;
using LibraryScore;

using System;
using System.Collections.Generic;
using System.Data.Entity;

using System.Linq;

using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;


namespace ISAI_APP.Controllers
{
    public class FindCropValidateController : Controller
    {
        // GET: FindCropValidate
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult FileVerification(HttpPostedFileBase file, string choose)
        {
            DataBaseJulio DataBase = new DataBaseJulio();
            string mensaje = string.Empty;
            if (file == null)
            {
                mensaje = "El archivo viene vacio";
                //return Json(mensaje);
            }

            Log objLog = new Log();
            objLog.Error = "Si llegue desde produccion" + "\n " + mensaje;
            DataBase.Logs.Add(objLog);
            DataBase.SaveChanges();

            /*modulo de pruebas*/
            objLog = new Log();
            var galleryDirectoryPath1 = Server.MapPath("~/Content/imagesUploads/");
            objLog.Error = galleryDirectoryPath1;
            DataBase.Logs.Add(objLog);
            DataBase.SaveChanges();

            System.Drawing.Bitmap bmpPostedImage = null;

            try
            {
                bmpPostedImage = new System.Drawing.Bitmap(file.InputStream);
                objLog.Error = "Creó la imagen bien";
                DataBase.Logs.Add(objLog);
                DataBase.SaveChanges();

                objLog = new Log();
                bmpPostedImage.Save(galleryDirectoryPath1 + file.FileName);
                objLog.Error = "Se guardó la imagen correctamente";
                DataBase.Logs.Add(objLog);
                DataBase.SaveChanges();
            }
            catch (Exception e)
            {
                objLog.Error = "Hubo error creando o guardando la imagen bien";
                DataBase.Logs.Add(objLog);
                DataBase.SaveChanges();
            }

            try
            {
                //FIND & CROP
                var imgToSave = FindAndCrop.FindCrop(bmpPostedImage, choose);
                objLog.Error = "La imagen se cortó chingón";
                DataBase.Logs.Add(objLog);
                DataBase.SaveChanges();

                if (imgToSave != null)
                {
                    var galleryDirectoryPath = Server.MapPath("~/Content/imagesCrop/");
                    string nombreImagen = "imagen" + DateTime.Now.ToString("yyyyMMddHHmmss") + ".jpg";
                    imgToSave.Save(galleryDirectoryPath + nombreImagen);

                    ViewBag.Url = nombreImagen;
                    ViewBag.Url2 = file.FileName;

                    try
                    {
                        //SCORE
                        var Lista = Score(nombreImagen);
                        objLog.Error = "Todo bien con el Score";
                        ViewBag.Lista = Lista;
                    }
                    catch (Exception e)
                    {
                        objLog.Error = "Error sacando Score";
                        DataBase.Logs.Add(objLog);
                        DataBase.SaveChanges();
                    }

                }
                else
                {
                    ViewBag.IsNull = "true";
                }
            }
            catch (Exception e)
            {
                objLog.Error = "Hubo error cortando la imagen o guardandola" + e.Message + "\nInner" + e.InnerException;
                DataBase.Logs.Add(objLog);
                DataBase.SaveChanges();
                if (e.Message.ToString() == "OpenCV: Bad input roi")
                {
                    ViewBag.IsNull = "true";
                    ViewBag.MensajeError = "Imagen demasiado pequeña para procesarse, favor de verificar";
                    
                }
                
            }

            return View();
        }

        public ActionResult Prueba()
        {

            return Json("null", JsonRequestBehavior.AllowGet);
        }

        public List<WeightedImages> Score(string nombreImagen)
        {
            ScoreImg score = new ScoreImg();
            var objeto = score.ProcessFolder(nombreImagen);

            return objeto;
        }
    }
}

ISAI APP/ISAI APP/Views/FindCropValidate/FileVerification.cshtml
@{
    /**/

    ViewBag.Title = "FileVerification";
}

<h2>Verificación de firma en INE, desde imagen adjuntada.</h2>
<hr />

@if (ViewBag.isNull == "true")
{
    if (ViewBag.MensajeError == null)
    {
        <div class="row">
            <h4><span class="badge badge-secondary">No se encontró la firma en la INE, favor de adjuntar una foto con mayor claridad.</span></h4>
        </div>
        <div class="row">
            <div class="col-md-12">
                <a class="btn btn-info col-md-12" href="/FindCropValidate/">Volver</a>
            </div>
        </div>
    }
    else
    {
        <div class="row">
            <h4><span class="badge badge-secondary">@ViewBag.MensajeError</span></h4>
        </div>
        <div class="row">
            <div class="col-md-12">
                <a class="btn btn-info col-md-12" href="/FindCropValidate/">Volver</a>
            </div>
        </div>
    }
}
else
{

    <div class="card-group">

        <div class="card">
            <div class="card-body">
                <img src="~/Content/imagesUploads/@ViewBag.Url2" class="img-fluid" alt="Credencial original">
                <h5 class="card-title"><strong> Imagen original. </strong></h5>
            </div>
        </div>

        <div class="card">
            <img src="~/Content/imagesCrop/@ViewBag.Url" class="img-fluid" alt="Credencial recortada">
            <div class="card-body">
                <h5 class="card-title"><strong> Imagen encontrada en imagen original. </strong></h5>

            </div>

        </div>
    </div>


    <br />
    <h2>Comparación de Imagenes.</h2>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-striped">
                <thead>
                    <tr align="center" |>
                        <th scope="col">Imagen</th>
                        <th scope="col">Porcentaje</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ViewBag.Lista)
                    {
                        <tr class="table-primary" align="center">
                            <td>
                                <img src="~/Content/documents/@item.ImagePath" width="130" height="145" alt="Credencial original" />
                            </td>
                            <td>@item.Score</td>

                        </tr>
                    }
                </tbody>

            </table>
        </div>
    </div>

    <div class="row" align="center">
        <div class="col-5 container">
            <button class="btn btn-danger container" type="submit">@Html.ActionLink("<<Regresar", "Index", "Home", null, new { @class = "my-class" })</button>
        </div>

        <div class="col-5 container">
            <button class="btn btn-success container" type="submit">@Html.ActionLink("Siguiente>>", "Index", "Home", null, new { @class = "my-class" })</button>
        </div>
    </div>


}@{
    ViewBag.Title = "FileVerification";
}

ISAI APP/ISAI APP/Views/FindCropValidate/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<script src="~/Scripts/sweet-alert.js"></script>
<link rel="stylesheet" href="~/Content/sweetalert/sweet-alert.css">

<h2>Find, Crop & Validate</h2>

<hr />

<div class="row">
    <div class="col-md-6 col-md-push-2">
        <section>

            @using (Ajax.BeginForm("FileVerification", "FindCropValidate", null, new AjaxOptions()
            {
                LoadingElementId = "Loading"
            }, new { enctype = "multipart/form-data" }))
            {
                <div>
                    <br />
                    <div class="row">
                        <div class="col-md-12">

                            <div class="input-group">
                                <h4>Ingresa INE</h4>
                            </div>
                            <div class="form-group">
                                <input type="file" id="idFile" name="file" class="form-control">
                            </div>
                            <div class="form-group">
                                <input type="radio" id="INE" name="choose" value="INE" checked />
                                <label for="INE"><strong>INE (buscar firma en reverso)</strong></label>
                            </div>
                            <div class="form-group">

                                <input type="radio" id="DOCUMENTO" name="choose" value="DOCUMENTO" />
                                <label for="DOCUMENTO"><strong>DOCUMENTO (buscar sello del escudo mexicano)</strong></label>
                            </div>
                            <div class="form-group">
                                <button id="idButtonVerificar" type="submit" class="btn btn-info btn-block">Verificar</button>
                                <div id="Loading" class="col-md-2" style="display: none;">
                                    <img src="~/Content/ImagesApp/loading.gif" width="50" height="50" alt="Loading...">
                                </div>
                            </div>
                            <hr />
                            <div class="form-group mx-auto">
                                <a href="/Home" class="btn btn-danger col-md-6" style="text-decoration:none">Regresar</a>
                            </div>

                        </div>
                    </div>
                </div>
            }

        </section>
    </div>
</div>


<script>
    $("#idButtonVerificar").click(function (e) {
        if ($('#idFile').get(0).files.length === 0) {
            Swal.fire({
                type: 'error',
                title: 'Elige un formato válido de imagen.'
            })
            e.preventDefault(); // Cancel the submit
            return false;
        } else {
            $('#Loading').show();
        }
    });
</script>