ISAI APP/ISAI APP/Controllers/HomeController.cs
using ISAI_APP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ISAI_APP.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
   
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public string Parametros(string name, string firstName, string lastName, string curp, string fechaNacimiento)
        {
            string Resultado = name + ' ' + firstName + ' ' + lastName + ' ' + ' ' + curp + ' ' + fechaNacimiento;
            ViewBag.Result = Resultado;
            return Resultado;
        }


        
    }
}

ISAI APP/ISAI APP/Controllers/OCRController.cs
using ISAI_APP.Models;
using ISAI_APP.OCR;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ISAI_APP.Controllers
{
    public class OCRController : Controller
    {
        // GET: OCR
        public ActionResult OCR()
        {
            return View();
        }

        public async Task<ActionResult> OCRVerification(HttpPostedFileBase file)
        {
            List<string> palabras = await OCRUtil.GetText(file);
            string fromPrincipal = Request["isPrincipal"];

            if (fromPrincipal != null)
            {
                INEData objOcr = FindCampos(palabras);
                return Json(objOcr, JsonRequestBehavior.AllowGet);
            }


            return Json(palabras, JsonRequestBehavior.AllowGet);
        }

        private static INEData EscenarioUno(List<string> palabras)
        {
            try
            {
                INEData ocr = new INEData();
                string textoPlano = String.Empty;
                var result0 = palabras.Where(x => x.Contains("NOMBRE")).ToArray();
                var result1 = palabras.Where(x => x.Contains("CURP")).ToArray();
                //Seccion nombre
                if (result0.Length > 0)
                {
                    int index = palabras.IndexOf(result0[0]);
                    ocr.firstName = palabras[index + 1];
                    ocr.lastName = palabras[index + 2];
                    ocr.name = palabras[index + 3];
                }
                //Seccion curp
                if (result1.Length > 0)
                {
                    int indexCurp = palabras.IndexOf(result1[0]);
                    ocr.CURP = palabras[indexCurp + 1];
                }
                //Seccion TextoArea
                ocr.textCompleto = palabras.ToArray();
                foreach (var texto in palabras.ToArray())
                {
                    textoPlano = textoPlano + " " + texto;
                }
                ocr.textComplete = textoPlano;


                if (ocr.firstName != null && ocr.lastName != null && ocr.name != null && ocr.textComplete != null)
                {
                    ocr.resultEnvironment = 1;
                    ocr.typeEnvironment = "Escenario 1";
                }
                else
                {
                    ocr.resultEnvironment = 0;
                    ocr.typeEnvironment = "No Funciono";
                }
                return ocr;
            }
            catch(Exception e)
            {
                e.Message.ToString();
                return null;
            }
        }

        private static INEData EscenarioDos(List<string> palabras)
        {
            try
            {
                INEData ocr = new INEData();
                string textoPlano = String.Empty;
                var result0 = palabras.Where(x => x.Contains("Ca")).ToArray();
                var result1 = palabras.Where(x => x.Contains("III")).ToArray();
                //Seccion nombre
                if (result0.Length > 0)
                {
                    int index = palabras.IndexOf(result0[0]);
                    ocr.firstName = palabras[index + 1];
                    ocr.lastName = palabras[index + 2];
                    ocr.name = palabras[index + 3];
                }
                //Seccion curp
                if (result1.Length > 0)
                {
                    int indexCurp = palabras.IndexOf(result1[0]);
                    ocr.CURP = palabras[indexCurp + 1];
                }
                //Seccion TextoArea
                ocr.textCompleto = palabras.ToArray();
                foreach (var texto in palabras.ToArray())
                {
                    textoPlano = textoPlano + " " + texto;
                }
                ocr.textComplete = textoPlano;


                if (ocr.firstName != null && ocr.lastName != null && ocr.name != null && ocr.textComplete != null)
                {
                    ocr.resultEnvironment = 1;
                    ocr.typeEnvironment = "Escenario 2";
                }
                else
                {
                    ocr.resultEnvironment = 0;
                    ocr.typeEnvironment = "No funciono";
                }
                return ocr;
            }
            catch (Exception e)
            {
                e.Message.ToString();
                return null;
            }
        }

        private static INEData FindCampos(List<string> palabras)
        {
            DataBaseJulio DataBase = new DataBaseJulio();
            INEData objOcr = new INEData();
            objOcr = EscenarioUno(palabras);
            try
            {
                if (objOcr.resultEnvironment == 1)
                {
                    objOcr.registerDate = DateTime.Now;
                    DataBase.INELogs.Add(objOcr);
                    DataBase.SaveChanges();
                    return objOcr;
            }
                else if (EscenarioDos(palabras).resultEnvironment == 1)
            {
                objOcr = EscenarioDos(palabras);
                objOcr.registerDate = DateTime.Now;
                DataBase.INELogs.Add(objOcr);
                DataBase.SaveChanges();
                return objOcr;
            }
            else
            {
                return null;
            }
        }
            catch (Exception e)
            {
                e.Message.ToString();
                return null;
            }
        }
    }
}

ISAI APP/ISAI APP/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ISAI APP/ISAI APP/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ISAI APP/ISAI APP/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<script src="~/Scripts/sweet-alert.js"></script>
<link rel="stylesheet" href="~/Content/sweetalert/sweet-alert.css">

<div class="card text-center">
    <div class="card-body">
        <h5 class="card-title">Validar Documento (OCR)</h5>
        <p class="card-text">Sube su INE por la parte de enfrente.</p>
        <div class="col-md-10 col-md-push-2">
            <section>

                @using (Html.BeginForm("OCRVerification", "OCR", FormMethod.Post, new { id = "fileUploadForm" }))
                {
                    <div>
                        <br />
                        <div class="row">
                            <div class="col-md-12">
                                <div class="row form-group">
                                    <input type="file" id="idFileDocumento" name="file" class="form-control" data-classButton="btn btn-primary" placeholder="Sube imagen">
                                    <hr />
                                </div>
                                <div class="row form-group">
                                    <input type="submit" id="idButton" class="btn btn-primary" value="Revisar Imagen" />
                                    <div id="Loading" class="col-md-2" style="display: none;">
                                        <img src="~/Content/ImagesApp/loading.gif" width="50" height="50" alt="Loading...">
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                }
            </section>
            <div class="row">
                <div class="col-lg-12">
                    <textarea id="txtArea" name="textarea" class="container" rows="10" cols="100">...</textarea>
                </div>
            </div>
        </div>

    </div>

</div>


<div class="row">
    <div class="col-md-12">
        <form method="post">
            <div class="form-group">
                <label for="txtName">Nombre:</label>
                <input id="txtName" class="form-control col-md-12" title="Nombre" value="" disabled />
            </div>
            <div class="form-group">
                <label for="txtName">Apellido Paterno:</label>
                <input id="txtApellidoPat" name="firstName" type="text" class="form-control col-md-12" title="Apellido Paterno" value="" disabled />
            </div>
            <div class="form-group">
                Apellido Materno: <input id="txtApellidoMat" name="lastName" type="text" class="form-control col-md-12" title="Apellido Materno" value="" disabled />
            </div>

            <div class="form-group">
                CURP: <input id="txtCURP" name="curp" type="text" class="form-control col-md-12" title="CURP" value="" disabled />
            </div>
            <div class="form-group">
                Hora: <input id="txtFechaNacimiento" name="fechaNacimiento" type="text" class="form-control col-md-12" title="Fecha de Nacimiento" value="" disabled />
                <div id="Console"></div>
            </div>
            <div class="form-group">
                <a class="btn btn-success btn-block" href="/FindCropValidate">Siguiente</a>
            </div>
        </form>
    </div>
</div>
<script>

function AddZero(num) {
    return (num >= 0 && num < 10) ? "0" + num : num + "";
}

window.onload = function() {
    var now = new Date();
    var strDateTime = [[AddZero(now.getDate()),
        AddZero(now.getMonth() + 1),
        now.getFullYear()].join("/"),
        [AddZero(now.getHours()),
        AddZero(now.getMinutes())].join(":"),
        now.getHours() >= 12 ? "PM" : "AM"].join(" ");
    document.getElementById("Console").innerHTML = "Now: " + strDateTime;
    };

    $("#idButton").click(function (e) {
        if ($('#idFileDocumento').get(0).files.length === 0) {
            Swal.fire({
                type: 'error',
                title: 'Elige un formato válido de imagen.'
            })
            e.preventDefault(); // Cancel the submit
            return false;
        } else {
            $('#Loading').show();
            $('#txtArea').empty();
            $('#txtArea').html('');
            debugger
            // Get form
            var form = $('#fileUploadForm')[0];

            // Create an FormData object
            var data = new FormData(form);
            data.append('isPrincipal', '1');

            $("#idButton").prop("disabled", true);

            $.ajax({
                type: "POST",
                enctype: 'multipart/form-data',
                url: '@Url.Action("OCRVerification", "OCR")',
                data: data,
                processData: false,
                contentType: false,
                cache: false,

                success: function (response) {
                    debugger

                    if (response == null) {
                        Swal.fire({type: 'error',title: 'Error al procesar imagen'})
                        return;
                    }

                    $("#idButton").prop("disabled", false);

                    $('#Loading').hide();

                    var arrayTextoCompleto = response.textCompleto;
                    var textoCompleto = "";

                    for (var i = 0; i < arrayTextoCompleto.length; i++) {
                        textoCompleto += arrayTextoCompleto[i] + " ";
                    }

                    $("#txtArea").val(response.textCompleto);
                    $("#txtName").val(response.name);
                    $("#txtApellidoPat").val(response.firstName);
                    $("#txtApellidoMat").val(response.lastName);
                    $("#txtCURP").val(response.CURP);

            },
            error: function (er) {
                Swal.fire({
                    type: 'error',
                    title: 'Error al buscar información en INE, favor de verificar la imagen.'
                })
                $("#idButton").prop("disabled", false);
                $('#Loading').hide();
            }//
        });//ajax
        }
    });


    @*var name = $('#txtName').val();
    var firstName = $('#txtFirstName').val();
    var lastName = $('#txtLastName').val();
    var fechaNacimiento = $('#txtFechaNacimiento').val();
    var curp = $('#txtCURP').val();

    $.ajax({
            url: '@Url.Action("Parametros", "Home")',
        contentType: "application/json; charset=utf-8",
        data: { 'name': name, 'firstName': firstName, 'lastName': lastName, 'fechaNacimiento': fechaNacimiento, 'CURP': curp },
            type: "GET",
            cache: false,
            success: function (response) {
            },
            error: function (er) {
                alert("error");

            }//

        });*@
</script>